{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales Raw Data\",\"Date\",\"Calculations\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.127.1235.0 (24.03)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "7c8cc0ce-037a-4a6c-a247-f8f11eafad20",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501"
      },
      {
        "name": "b7e0ca7f-726b-441a-962c-456a2d12da43",
        "fromColumn": "Start of Month",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c"
      },
      {
        "name": "19047c80-59bb-4145-865c-ce1f25556e00",
        "fromColumn": "End of Month",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad"
      },
      {
        "name": "e76db560-6c06-435b-8445-69eb7ad8bb41",
        "fromColumn": "Start of Week",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5"
      },
      {
        "name": "de3f0256-d839-44e1-85d4-ce8dc1e14a29",
        "fromColumn": "Date",
        "fromTable": "Sales Raw Data",
        "toColumn": "Date",
        "toTable": "Date"
      },
      {
        "name": "f50c9399-05f6-4d14-aab5-9b6e4e986739",
        "fromColumn": "Date",
        "fromTable": "Disconnected Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd"
      },
      {
        "name": "3b237f3a-c3bf-440d-ad21-cff64c3362aa",
        "fromColumn": "Start of Month",
        "fromTable": "Disconnected Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35"
      },
      {
        "name": "8e958b82-1e0f-415f-9393-5cf90c51023e",
        "fromColumn": "End of Month",
        "fromTable": "Disconnected Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf"
      },
      {
        "name": "bacc3aeb-854a-4ed8-8b4b-0742ab4924a7",
        "fromColumn": "Start of Week",
        "fromTable": "Disconnected Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7"
      },
      {
        "name": "f036d172-0311-48e0-a6e3-a17dd3504628",
        "fromColumn": "Product Category",
        "fromTable": "Sales Raw Data",
        "toColumn": "Product Category",
        "toTable": "Product Type Order"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Sales Raw Data",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9a34313-4860-4272-beb8-8bd6ad3b2e0d",
            "sourceColumn": "index",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "091cbad9-b1dc-4f2f-a341-5682e34f3749",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45b61b6e-c5e6-4c4a-8d83-36e2f1139d9a",
            "sourceColumn": "Customer Age",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "787c3302-68aa-4d0f-9f94-84101b64f2ff",
            "sourceColumn": "Customer Gender",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Country",
            "dataType": "string",
            "lineageTag": "8673d4e6-3256-4bc8-af24-7d27bf74ae1a",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "be22c250-13e7-49bc-88ef-e78cb483ec73",
            "sourceColumn": "State",
            "summarizeBy": "none"
          },
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3c09d2d-7efd-467c-b6c8-93db7c28384d",
            "sourceColumn": "Product Category",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2ff77ec7-54be-407b-90d1-6b0dca7fa947",
            "sourceColumn": "Sub Category",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "06d2c0f9-253d-4c87-86c9-3aa9bac1f802",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a809f158-ec63-48f6-944b-02e003eca234",
            "sourceColumn": "Unit Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c4534f23-f2c8-4f83-9d25-136ec5ee8b84",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0e8ee69b-8160-468e-9319-3e39fa16aaa1",
            "sourceColumn": "Cost",
            "summarizeBy": "sum"
          },
          {
            "name": "Revenue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cdefe47d-29d1-420f-8fa9-91c9d72b999f",
            "sourceColumn": "Revenue",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "574b55c2-7193-45d0-9083-d31339c78863",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0354df8-a4a1-4e90-aea4-05c31a56f119",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Birth Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "57bcac1a-fe8d-4e34-8035-3755d87f6a64",
            "sourceColumn": "Birth Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Generation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76040288-50f1-4e06-91b4-8e2b64322ae0",
            "sourceColumn": "Generation",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "27c51f3f-43d8-4b3d-93d4-7f4abc55c611",
        "measures": [
          {
            "name": "YTD Sales",
            "expression": "TOTALYTD(sum('Sales Raw Data'[Sales]),'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "c80b588f-848c-4fd0-88ce-2d0f6cd81d6c"
          },
          {
            "name": "SalesPerPoduct",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum('Sales Raw Data'[Sales]),ALLEXCEPT('Sales Raw Data','Sales Raw Data'[Product Category]))",
            "lineageTag": "08eb1b61-17d2-41d0-a82d-9d43d4f726ca"
          },
          {
            "name": "Sales ALL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum('Sales Raw Data'[Sales]), ALL('Sales Raw Data'[Product Category]))",
            "lineageTag": "42fe8b34-f8b8-4554-aef6-aef7d40504b9"
          }
        ],
        "partitions": [
          {
            "name": "Sales Raw Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\plesn\\Documents\\EasyAnalizy\\PBI_Dashboard\\Sales Dashboard\\salesforcourse-4fe2kehu.csv\"),[Delimiter=\",\", Columns=16, Encoding=1250, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Quantity\", type number}, {\"Unit Cost\", type number}, {\"Unit Price\", type number}, {\"Cost\", type number}, {\"Revenue\", type number}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"}),",
                "    #\"Changed Type with Locale\" = Table.TransformColumnTypes(#\"Removed Columns\", {{\"Date\", type date}}, \"en-US\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type with Locale\", each [Date] <> null and [Date] <> \"\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Year\", \"Month\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns1\",{{\"index\", Int64.Type}}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Changed Type1\", \"Sales\", each [Quantity]*[Unit Price]),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"Sales\", type number}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type2\", \"Profit\", each [Sales]-[Cost]),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Profit\", type number}}),",
                "    #\"Added Custom2\" = Table.AddColumn(#\"Changed Type3\", \"Birth Year\", each Number.From(Date.Year([Date]))-Number.From([Customer Age])),",
                "    #\"Changed Type4\" = Table.TransformColumnTypes(#\"Added Custom2\",{{\"Birth Year\", Int64.Type}}),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Changed Type4\", \"Generation\", each if [Birth Year] <= 1964 then \"Baby Boomers\" else if [Birth Year] <= 1980 then \"X\" else if [Birth Year] <= 1994 then \"Y (Millennials)\" else if [Birth Year] <= 2010 then \"Z (iGen)\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dcdfa268-57f5-4e59-8090-53dbb6008008",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "afa976af-4a43-40ca-af05-89c77cd83289",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e4634fe2-1ff7-4b25-9952-14e6bd38299a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d9e30490-9285-489e-96d4-510ec5315dda",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3aed6b5a-287a-44eb-a879-24a7a84691f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dbeaccb0-1154-4fe4-8bc5-faff629a6122",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e43791af-b41e-4f76-9f02-66f3ed9e830d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a05a94ef-3971-4831-91c5-4271902df55d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "622aabb2-6ad9-41e9-af6b-334afce8ec63",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "498a2728-87e1-4a58-b6c9-3c2c153e67ed",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e4516bcd-de83-47b3-b3c0-b94b00d2e23a",
                "ordinal": 3
              }
            ],
            "lineageTag": "ac6be306-f7b2-42a4-a38a-90e18c8f0448"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "1bed8605-83a1-4d7b-a551-69b62e64242d",
        "partitions": [
          {
            "name": "DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "49d1e6a2-95a7-4cc6-a522-e1f8c554d297",
            "sortByColumn": "Year",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501"
                },
                "isDefault": true,
                "relationship": "7c8cc0ce-037a-4a6c-a247-f8f11eafad20"
              }
            ]
          },
          {
            "name": "Date Integer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00197968-cf18-478c-8906-4a02e41f5914",
            "sourceColumn": "Date Integer",
            "summarizeBy": "sum"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb468cf3-d072-4ff1-896a-045d9d72260f",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "903538c1-760d-4f2b-b73e-6fb8f7e7b513",
            "sourceColumn": "Year Default",
            "summarizeBy": "none"
          },
          {
            "name": "YYYY-MM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23a73da0-cbfb-462c-a3d7-e4f83bca134d",
            "sourceColumn": "YYYY-MM",
            "summarizeBy": "none"
          },
          {
            "name": "Month-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9188c3ad-0c20-45b5-954b-5c46cbb49810",
            "sortByColumn": "YYYY-MM",
            "sourceColumn": "Month-Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab6757ab-ccb4-4861-ad73-3ae2484dea3e",
            "sourceColumn": "Month Of Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "74bee468-e048-40e8-b3f3-cd3f25542892",
            "sortByColumn": "Month Of Year",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "63d0bfd5-1109-4025-91a6-bf7801db2117",
            "sortByColumn": "Month Of Year",
            "sourceColumn": "Month Name Short",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7129a606-965b-4dd3-8275-bb912b551a28",
            "sourceColumn": "Month Name Default",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bc868933-a3ae-472e-939e-edb8b01a0bc4",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c"
                },
                "isDefault": true,
                "relationship": "b7e0ca7f-726b-441a-962c-456a2d12da43"
              }
            ]
          },
          {
            "name": "End of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1eeddb32-638f-44c3-a2a5-ec5d49e12948",
            "sourceColumn": "End of Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad"
                },
                "isDefault": true,
                "relationship": "19047c80-59bb-4145-865c-ce1f25556e00"
              }
            ]
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b00e8ab-d0a9-455c-83fb-3272fca92bdf",
            "sourceColumn": "Days in Month",
            "summarizeBy": "sum"
          },
          {
            "name": "ISO Weeknumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "31567206-c7ac-4227-82d6-e7b6c079d9e9",
            "sourceColumn": "ISO Weeknumber",
            "summarizeBy": "sum"
          },
          {
            "name": "ISO Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d64c3f6a-f2d7-432e-9008-009c406f753f",
            "sourceColumn": "ISO Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "578d7c74-6de5-40d2-b214-43d1aa0290ca",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5"
                },
                "isDefault": true,
                "relationship": "e76db560-6c06-435b-8445-69eb7ad8bb41"
              }
            ]
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c304509-3585-43ff-b31b-9e1a30bcd9fc",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "392d0858-426e-45f4-8d95-18394933c2b0",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Year-Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a5195d1e-dbe1-416f-bf51-94a0e08be7af",
            "sourceColumn": "Year-Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb339849-be70-4759-aafd-bab557818828",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          },
          {
            "name": "Day Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a15e3f7b-bfcb-4130-b2a0-221150915fae",
            "sortByColumn": "Day of Week Number",
            "sourceColumn": "Day Name Short",
            "summarizeBy": "none"
          },
          {
            "name": "Day of Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "49d70ad7-60cd-46f0-9c07-7e152a018e6b",
            "sourceColumn": "Day of Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "679b70b0-e4cf-4d29-a3ab-8de76cf8b9f3",
            "sourceColumn": "Day of Week Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e935495-9a13-4d9a-8704-b31872b1b9de",
            "sourceColumn": "Day of Year Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1b6df2c8-66f0-484b-be8e-890876acfa4d",
            "sourceColumn": "Day Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Week Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "280f1ea7-f699-4bbf-ae62-5c2920e7f8d0",
            "sourceColumn": "Week Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fc156280-1595-49ed-bcd0-bb08f93becad",
            "sourceColumn": "Month Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "da207e5a-1bdf-4385-bfef-ad2dd3fcdc05",
            "sourceColumn": "Quarter Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Year Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "21c57615-cf3a-4744-86ed-dc49525221cf",
            "sourceColumn": "Year Offset",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0716f99-ccbe-4d72-9fad-b1c2bd3ae487",
            "sourceColumn": "Is Weekend",
            "summarizeBy": "sum"
          },
          {
            "name": "Is Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5af6108-2c88-46a2-873a-9bb2ab1e7c11",
            "sourceColumn": "Is Weekday",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "ab84af9e-7a0b-4208-918b-6886cfe94ad4",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Today = Date.From( DateTime.LocalNow() ),",
                "    StartDate = #date(2015, 1, 1),",
                "    EndDate = Date.EndOfYear( Today ),",
                "    #\"List of Dates\" = List.Dates( StartDate, Duration.Days( EndDate - StartDate ) +1, #duration( 1, 0, 0, 0 ) ),",
                "    #\"Converted to Table\" = Table.FromList( #\"List of Dates\", Splitter.SplitByNothing(), type table[Date = Date.Type] ),",
                "    #\"Insert Date Integer\" = Table.AddColumn(#\"Converted to Table\", \"Date Integer\", each Number.From( Date.ToText( [Date], \"yyyyMMdd\" ) ), Int64.Type ),",
                "    #\"Insert Year\" = Table.AddColumn(#\"Insert Date Integer\", \"Year\", each Date.Year([Date]), Int64.Type),",
                "    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the Current period.",
                "    #\"Add Year Default\" = Table.AddColumn(#\"Insert Year\", \"Year Default\", each if Date.Year( Today ) = [Year] then \"Current\" else Text.From( [Year] ), type text),",
                "    #\"Insert YYYY-MM\" = Table.AddColumn(#\"Add Year Default\", \"YYYY-MM\", each Date.ToText( [Date], \"yyyy-MM\"), type text),",
                "    #\"Insert Month-Year\" = Table.AddColumn(#\"Insert YYYY-MM\", \"Month-Year\", each Date.ToText( [Date], \"MMM yyyy\"), type text),",
                "    #\"Insert Month Number\" = Table.AddColumn(#\"Insert Month-Year\", \"Month Of Year\", each Date.Month([Date]), Int64.Type),",
                "    #\"Insert Month Name\" = Table.AddColumn(#\"Insert Month Number\", \"Month Name\", each Date.MonthName([Date], \"EN-us\"), type text),",
                "    #\"Insert Month Name Short\" = Table.AddColumn(#\"Insert Month Name\", \"Month Name Short\", each Date.ToText( [Date] , \"MMM\", \"EN-us\" ), type text),",
                "    // Creates a dynamic year value called 'Current' that moves with the current date. Put this value in a slicer and it automatically switches to the current period.",
                "    #\"Add Month Name Default\" = Table.AddColumn(#\"Insert Month Name Short\", \"Month Name Default\", each if Date.Month( Today ) = [Month Of Year] then \"Current\" else [Month Name], type text ),",
                "    #\"Insert Start of Month\" = Table.AddColumn(#\"Add Month Name Default\", \"Start of Month\", each Date.StartOfMonth([Date]), type date),",
                "    #\"Inserted End of Month\" = Table.AddColumn(#\"Insert Start of Month\", \"End of Month\", each Date.EndOfMonth( [Date] ), type date),",
                "    #\"Inserted Days in Month\" = Table.AddColumn(#\"Inserted End of Month\", \"Days in Month\", each Date.DaysInMonth([Date]), Int64.Type),",
                "    #\"Add ISO Week\" = Table.AddColumn(#\"Inserted Days in Month\", \"ISO Weeknumber\", each let",
                "   CurrentThursday = Date.AddDays([Date], 3 - Date.DayOfWeek([Date], Day.Monday ) ),",
                "   YearCurrThursday = Date.Year( CurrentThursday ),",
                "   FirstThursdayOfYear = Date.AddDays(#date( YearCurrThursday,1,7),- Date.DayOfWeek(#date(YearCurrThursday,1,1), Day.Friday) ),",
                "   ISO_Week = Duration.Days( CurrentThursday - FirstThursdayOfYear) / 7 + 1",
                "in ISO_Week, Int64.Type ),",
                "    #\"Add ISO Year\" = Table.AddColumn(#\"Add ISO Week\", \"ISO Year\", each Date.Year(  Date.AddDays( [Date], 26 - [ISO Weeknumber] ) ), Int64.Type ),",
                "    #\"Insert Start of Week\" = Table.AddColumn(#\"Add ISO Year\", \"Start of Week\", each Date.StartOfWeek([Date], Day.Monday ), type date),",
                "    #\"Insert Quarter Number\" = Table.AddColumn(#\"Insert Start of Week\", \"Quarter Number\", each Date.QuarterOfYear([Date]), Int64.Type),",
                "    #\"Added Quarter\" = Table.AddColumn(#\"Insert Quarter Number\", \"Quarter\", each \"Q\" & Text.From( Date.QuarterOfYear([Date]) ), type text ),",
                "    #\"Add Year-Quarter\" = Table.AddColumn(#\"Added Quarter\", \"Year-Quarter\", each Text.From( Date.Year([Date]) ) & \"-Q\" & Text.From( Date.QuarterOfYear([Date]) ), type text ),",
                "    #\"Insert Day Name\" = Table.AddColumn(#\"Add Year-Quarter\", \"Day Name\", each Date.DayOfWeekName([Date], \"EN-us\" ), type text),",
                "    #\"Insert Day Name Short\" = Table.AddColumn( #\"Insert Day Name\", \"Day Name Short\", each Date.ToText( [Date], \"ddd\", \"EN-us\" ), type text),",
                "    #\"Insert Day of Month Number\" = Table.AddColumn(#\"Insert Day Name Short\", \"Day of Month Number\", each Date.Day([Date]), Int64.Type),",
                "    // Day.Monday indicates the week starts on Monday. Change this in case you want the week to start on a different date. ",
                "    #\"Insert Day of Week\" = Table.AddColumn(#\"Insert Day of Month Number\", \"Day of Week Number\", each Date.DayOfWeek( [Date], Day.Monday ), Int64.Type),",
                "    #\"Insert Day of Year\" = Table.AddColumn(#\"Insert Day of Week\", \"Day of Year Number\", each Date.DayOfYear( [Date] ), Int64.Type),",
                "    #\"Add Day Offset\" = Table.AddColumn(#\"Insert Day of Year\", \"Day Offset\", each Number.From( Date.From( Today ) - [Date] ) , Int64.Type ),",
                "    #\"Add Week Offset\" = Table.AddColumn(#\"Add Day Offset\", \"Week Offset\", each Duration.Days( Date.StartOfWeek( [Date], Day.Monday ) - Date.StartOfWeek( Today, Day.Monday ) ) / 7 , Int64.Type ),",
                "    #\"Add Month Offset\" = Table.AddColumn(#\"Add Week Offset\", \"Month Offset\", each ( [Year] - Date.Year( Today ) ) * 12 + ( [Month Of Year] - Date.Month( Today ) ), Int64.Type ),",
                "    #\"Add Quarter Offset\" = Table.AddColumn(#\"Add Month Offset\", \"Quarter Offset\", each ( [Year] - Date.Year(Today) ) * 4 + Date.QuarterOfYear( [Date] ) - Date.QuarterOfYear( Today ), Int64.Type ),",
                "    #\"Add Year Offset\" = Table.AddColumn(#\"Add Quarter Offset\", \"Year Offset\", each [Year] - Date.Year(Today), Int64.Type ),",
                "    #\"Insert Is Weekend\" = Table.AddColumn(#\"Add Year Offset\", \"Is Weekend\", each if Date.DayOfWeek( [Date] ) >= 5 then 1 else 0, Int64.Type ),",
                "    #\"Insert Is Weekday\" = Table.AddColumn(#\"Insert Is Weekend\", \"Is Weekday\", each if Date.DayOfWeek( [Date] ) < 5 then 1 else 0, Int64.Type )",
                "in",
                "    #\"Insert Is Weekday\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a65bba7-a424-4b5c-b609-2f4bdbafb2f1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "79d588d3-bd22-4e2b-a5e3-df0e514b7fb0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4284ee54-2396-4b7a-b2a8-e5bb57b981dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "8ca92fb4-8c4e-4e88-92ec-cd50024ad2c2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "210d200b-1d8e-4d67-9d3b-a676825c182e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7a83fe1c-706f-4c80-bf53-bb1b274f338b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b39b124f-1da6-4bd3-a791-3f96c8608871",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b703806d-ba59-4b39-818b-d28970f0b6d7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "54baa840-cd85-4932-9f24-3b67edc28bd5",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b46cb262-cf08-45d5-88a4-0a6572d6ee48",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8197ba86-4fda-4b6f-8ffe-21998ab38fe5",
                "ordinal": 3
              }
            ],
            "lineageTag": "0376de5e-95ae-48d6-907c-84330125ae14"
          }
        ],
        "isHidden": true,
        "lineageTag": "9f63be93-e688-4779-bcdd-9a4b8d4f0b21",
        "partitions": [
          {
            "name": "LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e119b42d-28b3-4036-8554-cf1ccfad6dda",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "238d5fd1-ecaf-4104-a5b1-26db488e9800",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "66fd5b4d-68b2-4023-b1b4-93d08e2a2304",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "644b73ed-c37c-4b29-977b-fce91d9f5322",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d6a33f25-151a-4e6b-839f-43f4090fe10e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "496ca501-25fe-49c8-af75-081726f9eebb",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4b68a02c-bf1e-4b21-b24c-2abad608adbf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "31036582-afb9-436a-b424-a9087ecd2ecd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "597cd50d-7180-42b8-9153-ebf5e52411ba",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "cdd37ff4-3aa9-4eb0-808e-48f7ce6f5b4b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cd6c569d-e93e-4ce3-8f52-c19caf610a1a",
                "ordinal": 3
              }
            ],
            "lineageTag": "683cf214-ea75-4a58-9cee-ab7a96e440f4"
          }
        ],
        "isHidden": true,
        "lineageTag": "1f8e433c-44ce-4ff4-a08e-06b8243cf398",
        "partitions": [
          {
            "name": "LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Start of Month])), 1, 1), Date(Year(MAX('Date'[Start of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "59e39564-0ad3-4c3b-84d1-7d7e83539046",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d77a60b8-7109-473f-a067-40749dd7b760",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "10be7544-e4c6-4183-8662-ff03caefbbc5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "be668887-9b73-4a9a-b6fc-7bd9ddf178a6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8843aa95-016e-49e7-877d-8049d74103c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "cb9d9373-1cd4-47eb-aa6c-b745c93a91b4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "622cd93d-7527-4690-b707-e25aaa292448",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9984d34a-7f61-4309-af51-4ef30374fdd2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "32d315a1-dbf9-4be2-a75e-4823fe7b061f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d074e473-b480-4255-92f8-7a988e765e2d",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "183075f0-b460-4658-b9d3-58a5b590a98f",
                "ordinal": 3
              }
            ],
            "lineageTag": "9f53dc31-3737-410b-9dd3-759bfcb4de26"
          }
        ],
        "isHidden": true,
        "lineageTag": "601ebdb1-b84d-47a1-aedc-64affa9b5a03",
        "partitions": [
          {
            "name": "LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[End of Month])), 1, 1), Date(Year(MAX('Date'[End of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e6342e37-df51-4eee-871b-7939b01ade5e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "03e01ce3-a920-43bf-99ea-a83a17f0b873",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7f8c472b-f7a5-4ea9-9539-1de993311139",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ecbf69c1-bbcd-4098-867c-2de092ea63ee",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c08b0cd1-f14f-4540-88c5-fdcca1afaea5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e8c5787e-c526-4a4d-994d-df2f58c5a29b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3ff4420a-e2b2-4ba3-a9da-1222b7f960a2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7d1a4d4f-f4d2-4e56-b839-c3cabd1b778e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6937cd2c-9b16-4fdb-9a10-7e43eb58aac3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b160ef76-34d5-4d71-a8ac-11f5c95656cc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b4b8b31f-92d5-408c-9914-4d54b603ce59",
                "ordinal": 3
              }
            ],
            "lineageTag": "7a71cfa1-3aef-4129-8a4b-52e93a012abe"
          }
        ],
        "isHidden": true,
        "lineageTag": "bb5459ca-9fc1-414a-9866-3d2065db6f85",
        "partitions": [
          {
            "name": "LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Start of Week])), 1, 1), Date(Year(MAX('Date'[Start of Week])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calculations",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "107fa4a1-c98b-4faa-91c3-e59251f800c6",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85957004-9db1-47c8-b19e-bfa89bb08725",
        "measures": [
          {
            "name": "BarToHighlight",
            "expression": [
              "",
              "VAR _slectedmth=VALUES('Disconnected Date'[Month Name])",
              "VAR _mthtohighlight=SELECTEDVALUE('Date'[Month Name])",
              "VAR _filtered= ISFILTERED('Disconnected Date'[Month Name])",
              "VAR _result=SWITCH(TRUE, NOT(_filtered), \"#136862\",",
              "            _mthtohighlight IN _slectedmth",
              "            && _filtered,  \"#136862\",  \"#FFE4AD\")",
              "RETURN",
              "_result"
            ],
            "lineageTag": "582504cd-e04a-47cc-9bf3-e714942b4a34"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Sales Raw Data'[Sales]))",
            "lineageTag": "413681e5-d124-4c4b-91e4-7897c3e186ef"
          },
          {
            "name": "Total Profit",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Sales Raw Data'[Profit]))",
            "lineageTag": "0480a256-450b-483f-8a09-756409c5a222"
          },
          {
            "name": "Total Units",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(SUM('Sales Raw Data'[Quantity]))",
            "lineageTag": "b25e5101-87d5-4010-b9f6-23d04c2d028a"
          },
          {
            "name": "Total Margine",
            "expression": "DIVIDE([Total Profit],[Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5a0ec50f-ffab-49a8-a27a-e67a1cbef85c"
          },
          {
            "name": "Total Profit (PM)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Profit], PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "fa3c1160-065e-4b32-9daa-e740bc92678d"
          },
          {
            "name": "Total Sales (PM)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Sales], PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "b140c3b2-778e-406c-bd64-f3e3f9c6ce0f"
          },
          {
            "name": "Total Units (PM)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Units], PREVIOUSMONTH('Date'[Date]))",
            "lineageTag": "321629f1-0232-48e5-a63d-264df47334d7"
          },
          {
            "name": "Total Margine (PM)",
            "expression": "DIVIDE([Total Profit (PM)],[Total Sales (PM)])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "71b9da36-a633-4331-9f65-7d7598946e48"
          },
          {
            "name": "Total Sales Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Sales]-[Total Sales (PM)]",
            "lineageTag": "e46df070-282b-4f47-b4da-f5f4cf185317"
          },
          {
            "name": "Prev Mth Selected",
            "expression": [
              "",
              "VAR _prevmth= CALCULATE(max('Date'[Month Name]),PREVIOUSMONTH('Date'[Date])) & \" (PM):\"",
              "",
              "return",
              "IF(ISBLANK([Total Sales]), Blank(), _prevmth)",
              "",
              ""
            ],
            "lineageTag": "909a8024-a8a3-4587-9527-94e7553b2250"
          },
          {
            "name": "Total Sales Var %",
            "expression": "DIVIDE([Total Sales Var],[Total Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dc3e37a4-d3bf-4b48-91f0-74d22387f790"
          },
          {
            "name": "Total Sales Var % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[Total Sales Var %]",
              "VAR _varnum= [Total Sales Var]",
              "VAR _blank= ISBLANK([Total Sales])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "65dc6d9a-f745-4ace-93ff-e2125d321f93"
          },
          {
            "name": "Total Units Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Units]-[Total Units (PM)]",
            "lineageTag": "e94ad5f5-6dd4-425a-9a93-a683d0132a4d"
          },
          {
            "name": "Total Units Var %",
            "expression": "DIVIDE([Total Units Var], [Total Units])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b7b73377-7f72-4ea6-88a6-992daaa3df98"
          },
          {
            "name": "Total Units Var % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[Total Units Var %]",
              "VAR _varnum= [Total Units Var]",
              "VAR _blank= ISBLANK([Total Units])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "66858863-e76d-4359-b737-aed160c3c3b0"
          },
          {
            "name": "Total Profit Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Profit]-[Total Profit (PM)]",
            "lineageTag": "0903cc26-bcf7-4f25-8ea6-e179939b91c3"
          },
          {
            "name": "Total Profit Var %",
            "expression": "DIVIDE([Total Profit Var],[Total Profit])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "35e2d1c6-8c3f-4265-a7b8-d0af29245544"
          },
          {
            "name": "Total Profit Var % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[Total Profit Var %]",
              "VAR _varnum= [Total Profit Var]",
              "VAR _blank= ISBLANK([Total Profit])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "209d4776-0229-48ae-8b39-3bd9cc79a24c"
          },
          {
            "name": "Total Margine Var",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Total Margine]-[Total Margine (PM)]",
            "lineageTag": "1ff1f819-582c-46b5-a59b-769917c4700a"
          },
          {
            "name": "Total Margine Var %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE([Total Margine Var],[Total Margine])",
            "lineageTag": "93bf1297-1094-414b-a82e-e6ba2a95a5f6"
          },
          {
            "name": "Total Margine Var % Arrow",
            "expression": [
              "",
              "",
              "VAR _upparr=UNICHAR(129129)",
              "VAR _darr=UNICHAR(129131)",
              "VAR _varperc=[Total Margine Var %]",
              "VAR _varnum= [Total Margine Var]",
              "VAR _blank= ISBLANK([Total Margine])",
              "return",
              "If (_blank, blank(), IF(_varnum>0, round(_varperc,2)*100 & \"% \" & _upparr,",
              "                                round(_varperc,2)*100 & \"% \" & _darr))"
            ],
            "lineageTag": "de3acf71-bfa7-4b5c-a7c9-00ae9cef6ff3"
          },
          {
            "name": "YTD Profit",
            "expression": "TOTALYTD([Total Profit],'Date'[Date])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "bd285129-df0f-4dfb-bb02-9ccf7d9c7159"
          },
          {
            "name": "MTD Sales",
            "expression": "CALCULATE([Total Sales],DATESMTD('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "275cc5b3-bca9-4d7d-b3f2-3c53af359951"
          },
          {
            "name": "LY Sales",
            "expression": "CALCULATE([Total Sales], PREVIOUSYEAR('Date'[Date]))",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "lineageTag": "6f02185c-c948-435a-bb8a-38a63ae65f80"
          },
          {
            "name": "Highlight Bar",
            "expression": [
              "",
              "VAR _highest=MAXX(ALLSELECTED('Date'[Month-Year]),[Total Sales])",
              "VAR _lowest=MINX(ALLSELECTED('Date'[Month-Year]),[Total Sales])",
              "VAR _RESULT=SWITCH(TRUE(), _highest=[Total Sales], \"#9EBFB8\",",
              "                            _lowest=[Total Sales], \"#EFB5B9\",",
              "                            \"#FFE4AD\")",
              "RETURN",
              "_RESULT"
            ],
            "lineageTag": "1f0c593c-a7a7-469d-9ac7-27f8e625176d"
          },
          {
            "name": "highest",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MAXX(ALLEXCEPT('Date','Date'[Month Name]),[Total Sales])",
            "lineageTag": "41cb0156-309a-4ebb-b9dc-7f2b2d95f4f8"
          },
          {
            "name": "BarToHighlight_v3",
            "expression": [
              "",
              "VAR _Mth=ALLSELECTED('Date'[Day Name Short],'Date'[Day of Week Number])",
              "VAR _currSales=[Total Sales]",
              "VAR _rank=RANKX(_Mth, [Total Sales],_currSales,DESC)",
              "VAR _result= If(_rank<=[Parameter Value], \"#136862\", \"#FFE4AD\")",
              "RETURN",
              "_result"
            ],
            "lineageTag": "39165bad-f423-4b61-bac4-3c98c1c6b547"
          },
          {
            "name": "Sales Variance Center",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MAXX(ALLSELECTED('Sales Raw Data'[Sub Category]),[Total Units])*1.5",
            "lineageTag": "c78c72fd-612e-48eb-b3db-eeefb9ca98d9"
          },
          {
            "name": "Sales 2016",
            "expression": "CALCULATE([Total Sales],'Date'[Year]=YEAR(Date(2016,1,1)))",
            "formatString": "0",
            "lineageTag": "9c355f74-65cf-4242-b8f2-b07f42de16ec"
          },
          {
            "name": "Sales 2015",
            "expression": "CALCULATE([Total Sales],'Date'[Year]=YEAR(Date(2015,1,1)))",
            "formatString": "0",
            "lineageTag": "9a6f5a06-8ec7-4893-99f2-48bbae76ceea"
          },
          {
            "name": "Sales Variance",
            "expression": "[Total Units]-[Total Units (PM)]",
            "formatString": "0",
            "lineageTag": "6df82d2a-3c35-46ed-b66e-7d48c202eba6"
          },
          {
            "name": "Sales Variance positive",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If ([Total Sales]>[Total Sales (PM)], [Sales Variance])",
            "lineageTag": "da39c989-67b6-47f9-a16b-6072bd22b579"
          },
          {
            "name": "Sales Variance Dummy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Sales Variance Center]",
            "lineageTag": "6837b4d8-716c-42eb-933d-3b42c5c7d330"
          },
          {
            "name": "Sales Variance negative",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "If ([Total Sales]<[Total Sales (PM)], [Sales Variance])",
            "lineageTag": "8c1c071b-168a-4575-983c-a36a78a1e302"
          },
          {
            "name": "lbl position left",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "if([Total Units]<[Total Units (PM)],[Sales Variance Center]+[Sales Variance])",
            "lineageTag": "baf33b53-d5a3-4533-a8ad-56f29790e4a0"
          },
          {
            "name": "lbl position right",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "if([Total Units]>[Total Units (PM)],[Sales Variance Center]+[Sales Variance])",
            "lineageTag": "a068b0d8-c6bb-4772-a7ee-08c8560ada57"
          },
          {
            "name": "Filters Applied",
            "expression": [
              "",
              "VAR MaxFilters = 3",
              "RETURN",
              "IF ( ",
              "    ISFILTERED ( 'Calculations'[Column1] ), ",
              "    VAR ___f = FILTERS ( 'Calculations'[Column1] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Calculations'[Column1] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Calculations'[Column1], \", \" )",
              "    VAR ___x = \"'Calculations'[Column1] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Date], \", \" )",
              "    VAR ___x = \"'Date'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Date Integer] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Date Integer] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Date Integer] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Date Integer], \", \" )",
              "    VAR ___x = \"'Date'[Date Integer] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day Name] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day Name], \", \" )",
              "    VAR ___x = \"'Date'[Day Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day Name Short] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day Name Short] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day Name Short] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day Name Short], \", \" )",
              "    VAR ___x = \"'Date'[Day Name Short] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day of Month Number] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day of Month Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day of Month Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day of Month Number], \", \" )",
              "    VAR ___x = \"'Date'[Day of Month Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day of Week Number] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day of Week Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day of Week Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day of Week Number], \", \" )",
              "    VAR ___x = \"'Date'[Day of Week Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day of Year Number] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day of Year Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day of Year Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day of Year Number], \", \" )",
              "    VAR ___x = \"'Date'[Day of Year Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Day Offset] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Day Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Day Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Day Offset], \", \" )",
              "    VAR ___x = \"'Date'[Day Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Days in Month] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Days in Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Days in Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Days in Month], \", \" )",
              "    VAR ___x = \"'Date'[Days in Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[End of Month] ), ",
              "    VAR ___f = FILTERS ( 'Date'[End of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[End of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[End of Month], \", \" )",
              "    VAR ___x = \"'Date'[End of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Is Weekday] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Is Weekday] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Is Weekday] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Is Weekday], \", \" )",
              "    VAR ___x = \"'Date'[Is Weekday] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Is Weekend] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Is Weekend] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Is Weekend] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Is Weekend], \", \" )",
              "    VAR ___x = \"'Date'[Is Weekend] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[ISO Weeknumber] ), ",
              "    VAR ___f = FILTERS ( 'Date'[ISO Weeknumber] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[ISO Weeknumber] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[ISO Weeknumber], \", \" )",
              "    VAR ___x = \"'Date'[ISO Weeknumber] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[ISO Year] ), ",
              "    VAR ___f = FILTERS ( 'Date'[ISO Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[ISO Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[ISO Year], \", \" )",
              "    VAR ___x = \"'Date'[ISO Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month Name] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month Name], \", \" )",
              "    VAR ___x = \"'Date'[Month Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month Name Default] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month Name Default] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month Name Default] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month Name Default], \", \" )",
              "    VAR ___x = \"'Date'[Month Name Default] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month Name Short] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month Name Short] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month Name Short] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month Name Short], \", \" )",
              "    VAR ___x = \"'Date'[Month Name Short] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month Of Year] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month Of Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month Of Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month Of Year], \", \" )",
              "    VAR ___x = \"'Date'[Month Of Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month Offset] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month Offset], \", \" )",
              "    VAR ___x = \"'Date'[Month Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Month-Year] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Month-Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Month-Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Month-Year], \", \" )",
              "    VAR ___x = \"'Date'[Month-Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Quarter], \", \" )",
              "    VAR ___x = \"'Date'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Quarter Number] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Quarter Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Quarter Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Quarter Number], \", \" )",
              "    VAR ___x = \"'Date'[Quarter Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Quarter Offset] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Quarter Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Quarter Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Quarter Offset], \", \" )",
              "    VAR ___x = \"'Date'[Quarter Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Start of Month] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Start of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Start of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Start of Month], \", \" )",
              "    VAR ___x = \"'Date'[Start of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Start of Week] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Start of Week] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Start of Week] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Start of Week], \", \" )",
              "    VAR ___x = \"'Date'[Start of Week] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Week Offset] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Week Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Week Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Week Offset], \", \" )",
              "    VAR ___x = \"'Date'[Week Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Year] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Year], \", \" )",
              "    VAR ___x = \"'Date'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Year Default] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Year Default] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Year Default] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Year Default], \", \" )",
              "    VAR ___x = \"'Date'[Year Default] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Year Offset] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Year Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Year Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Year Offset], \", \" )",
              "    VAR ___x = \"'Date'[Year Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[Year-Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Date'[Year-Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[Year-Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[Year-Quarter], \", \" )",
              "    VAR ___x = \"'Date'[Year-Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Date'[YYYY-MM] ), ",
              "    VAR ___f = FILTERS ( 'Date'[YYYY-MM] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Date'[YYYY-MM] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Date'[YYYY-MM], \", \" )",
              "    VAR ___x = \"'Date'[YYYY-MM] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Date] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Date], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Day] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Day], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Month] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Month], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[MonthNo], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Quarter], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[QuarterNo], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Year] ), ",
              "    VAR ___f = FILTERS ( 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Year], \", \" )",
              "    VAR ___x = \"'DateTableTemplate_2999223d-81d5-45af-80fd-4cb56e6d40f1'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Date], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Date Integer] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Date Integer] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Date Integer] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Date Integer], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Date Integer] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day Name] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day Name], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day Name Short] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day Name Short] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day Name Short] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day Name Short], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day Name Short] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day of Month Number] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day of Month Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day of Month Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day of Month Number], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day of Month Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day of Week Number] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day of Week Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day of Week Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day of Week Number], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day of Week Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day of Year Number] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day of Year Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day of Year Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day of Year Number], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day of Year Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Day Offset] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Day Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Day Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Day Offset], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Day Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Days in Month] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Days in Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Days in Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Days in Month], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Days in Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[End of Month] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[End of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[End of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[End of Month], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[End of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Is Weekday] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Is Weekday] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Is Weekday] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Is Weekday], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Is Weekday] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Is Weekend] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Is Weekend] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Is Weekend] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Is Weekend], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Is Weekend] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[ISO Weeknumber] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[ISO Weeknumber] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[ISO Weeknumber] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[ISO Weeknumber], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[ISO Weeknumber] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[ISO Year] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[ISO Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[ISO Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[ISO Year], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[ISO Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month Name] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month Name], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month Name] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month Name Default] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month Name Default] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month Name Default] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month Name Default], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month Name Default] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month Name Short] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month Name Short] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month Name Short] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month Name Short], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month Name Short] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month Of Year] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month Of Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month Of Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month Of Year], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month Of Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month Offset] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month Offset], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Month-Year] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Month-Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Month-Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Month-Year], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Month-Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Quarter], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Quarter Number] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Quarter Number] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Quarter Number] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Quarter Number], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Quarter Number] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Quarter Offset] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Quarter Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Quarter Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Quarter Offset], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Quarter Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Start of Month] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Start of Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Start of Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Start of Month], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Start of Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Start of Week] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Start of Week] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Start of Week] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Start of Week], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Start of Week] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Week Offset] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Week Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Week Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Week Offset], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Week Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Year] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Year], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Year Default] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Year Default] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Year Default] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Year Default], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Year Default] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Year Offset] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Year Offset] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Year Offset] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Year Offset], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Year Offset] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[Year-Quarter] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[Year-Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[Year-Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[Year-Quarter], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[Year-Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Disconnected Date'[YYYY-MM] ), ",
              "    VAR ___f = FILTERS ( 'Disconnected Date'[YYYY-MM] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Disconnected Date'[YYYY-MM] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Disconnected Date'[YYYY-MM], \", \" )",
              "    VAR ___x = \"'Disconnected Date'[YYYY-MM] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_39b68a36-9004-4e40-ac87-a3ae9979262c'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_4c9ea8d8-274f-42b6-ac6f-aa6899bef0ad'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_771ae1fe-5725-494c-a7de-042eba5cf501'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_9b55ee23-fe67-42b8-a928-8b19ab270be5'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Date] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Date], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Day] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Day] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Day] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Day], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Day] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Month] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Month] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Month] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Month], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Month] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[MonthNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[MonthNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[MonthNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[MonthNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[MonthNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Quarter] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Quarter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Quarter] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Quarter], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Quarter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[QuarterNo] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[QuarterNo] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[QuarterNo] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[QuarterNo], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[QuarterNo] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Year] ), ",
              "    VAR ___f = FILTERS ( 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Year], \", \" )",
              "    VAR ___x = \"'LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd'[Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( Parameter[Parameter] ), ",
              "    VAR ___f = FILTERS ( Parameter[Parameter] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, Parameter[Parameter] )",
              "    VAR ___d = CONCATENATEX ( ___t, Parameter[Parameter], \", \" )",
              "    VAR ___x = \"Parameter[Parameter] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Birth Year] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Birth Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Birth Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Birth Year], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Birth Year] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Cost] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Cost] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Cost] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Cost], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Cost] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Country] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Country] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Country] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Country], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Country] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Customer Age] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Customer Age] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Customer Age] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Customer Age], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Customer Age] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Customer Gender] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Customer Gender] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Customer Gender] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Customer Gender], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Customer Gender] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Date] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Date] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Date] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Date], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Date] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Generation] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Generation] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Generation] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Generation], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Generation] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[index] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[index] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[index] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[index], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[index] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Product Category] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Product Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Product Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Product Category], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Product Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Profit] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Profit] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Profit] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Profit], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Profit] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Quantity] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Quantity] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Quantity] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Quantity], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Quantity] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Revenue] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Revenue] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Revenue] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Revenue], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Revenue] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Sales] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Sales] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Sales] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Sales], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Sales] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[State] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[State] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[State] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[State], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[State] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Sub Category] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Sub Category] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Sub Category] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Sub Category], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Sub Category] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Unit Cost] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Unit Cost] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Unit Cost] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Unit Cost], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Unit Cost] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( 'Sales Raw Data'[Unit Price] ), ",
              "    VAR ___f = FILTERS ( 'Sales Raw Data'[Unit Price] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, 'Sales Raw Data'[Unit Price] )",
              "    VAR ___d = CONCATENATEX ( ___t, 'Sales Raw Data'[Unit Price], \", \" )",
              "    VAR ___x = \"'Sales Raw Data'[Unit Price] = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              "---- MODEL MEASURES END ----",
              "",
              ""
            ],
            "lineageTag": "850d6114-c5ca-4d10-9e03-617b2cfe352e"
          },
          {
            "name": "Header",
            "expression": [
              "",
              "VAR _header_main=\"Period from Year 2015-2016\"",
              "Return",
              "_header_main"
            ],
            "lineageTag": "7605ee8c-b8a9-4f2d-b9ee-a5ae69eb0860"
          },
          {
            "name": "Title_Product_Sales",
            "expression": [
              "",
              "VAR _year=SELECTEDVALUE('Date'[Year])",
              "VAR _mth=SELECTEDVALUE('Date'[Month Name])",
              "VAR _country=SELECTEDVALUE('Sales Raw Data'[Country])",
              "VAR _city=SELECTEDVALUE('Sales Raw Data'[State])",
              "VAR _prod=SELECTEDVALUE('Sales Raw Data'[Sub Category])",
              "VAR subtitles=\"for \" & _year & \" |\" & _mth  & \" |\" & _country  & \" |\" &_city",
              "RETURN",
              "subtitles"
            ],
            "lineageTag": "16a56074-0eb5-46bc-850c-87d633ba2512"
          },
          {
            "name": "subTitle_Sales_bySubProd",
            "expression": [
              "",
              "VAR _year=SELECTEDVALUE('Date'[Year])",
              "VAR _mth=SELECTEDVALUE('Date'[Month Name])",
              "VAR _country=SELECTEDVALUE('Sales Raw Data'[Country])",
              "VAR _city=SELECTEDVALUE('Sales Raw Data'[State])",
              "VAR _prod=SELECTEDVALUE('Sales Raw Data'[Sub Category])",
              "VAR subtitles=_year & \" \" &_mth &\" vs. Previous Month\" & \"|\" & _country  & \" |\" &_city",
              "RETURN",
              "subtitles"
            ],
            "lineageTag": "c5d68be2-d341-4dfb-ab82-b2afbf493ad9"
          },
          {
            "name": "Bike Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Sales], 'Sales Raw Data'[Product Category]=\"Bikes\")",
            "lineageTag": "e540a228-ba7f-417d-ad60-20fa5b097735"
          },
          {
            "name": "Clothing Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Sales], 'Sales Raw Data'[Product Category]=\"Clothing\")",
            "lineageTag": "b848de5a-754a-47ed-b7df-b9d9e3151390"
          },
          {
            "name": "Accessories Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Total Sales], 'Sales Raw Data'[Product Category]=\"Accessories\")",
            "lineageTag": "fb10fc90-338b-461d-b75a-5d4a606a4d31"
          },
          {
            "name": "Bike_Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Total Sales]-[Bike Total Sales]"
            ],
            "lineageTag": "347a4b7b-7e1b-49cd-bc28-063648915667"
          },
          {
            "name": "Clothing_Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Total Sales]-[Clothing Total Sales]"
            ],
            "lineageTag": "8a595966-eeb8-4e5c-88e0-4da259eee325"
          },
          {
            "name": "Accessories_Diff",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "[Total Sales]-[Accessories Total Sales]"
            ],
            "lineageTag": "361a7b6e-3eb6-467b-b854-7d0c28af72c8"
          },
          {
            "name": "Clothing Dummy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([Clothing_Diff]+[Clothing Total Sales])*(1/3)",
            "lineageTag": "de02d74c-bf0c-475f-b9c8-83637392c93f"
          },
          {
            "name": "Accessories Dummy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([Accessories_Diff]+[Accessories Total Sales])*(1/3)",
            "lineageTag": "2fa67389-c749-4b95-a843-c9a9cef64723"
          },
          {
            "name": "Bike Dummy",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "([Bike_Diff]+[Bike Total Sales])*(1/3)",
            "lineageTag": "61cbf2be-20b0-4b49-9e3d-b8026b82b9a5"
          },
          {
            "name": "Header 2",
            "expression": [
              "",
              "VAR _header_main=\"Financial Overview\"",
              "Return",
              "_header_main"
            ],
            "lineageTag": "dfda55ba-922b-406f-b7dc-a2b2f320cdb5"
          },
          {
            "name": "Filled Dot icone",
            "expression": "\"\"",
            "lineageTag": "46bfd279-d649-4895-b721-58f688bbbc42"
          },
          {
            "name": "Dot icone",
            "expression": "\"\"",
            "lineageTag": "ca2a1df3-a9c4-44dc-b247-5fe2bf1aa9da"
          },
          {
            "name": "Mth2Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD([Total Sales], 'Date'[Date])",
            "lineageTag": "f9baaae7-9dfe-455d-b7ea-71fc39efbb04"
          },
          {
            "name": "PM_Mth2Date",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "TOTALMTD([Total Sales (PM)], 'Date'[Date])",
            "lineageTag": "8b095f1b-6043-4370-8d69-9a461d25c8f2"
          },
          {
            "name": "Y icone",
            "expression": [
              "",
              "VAR _current_mth=CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\")",
              "VAR _pm_mth=CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\")",
              "VAR _mom=DIVIDE(_current_mth,_pm_mth)*100",
              "VAR _icone_rep=IF(_mom>100, 10,ROUND(_mom/10,0))",
              "VAR _final= REPT([Filled Dot icone],_icone_rep)& REPT([Dot icone],10-_icone_rep)",
              "Return",
              "_final"
            ],
            "lineageTag": "bbec887c-09a5-461e-98dc-286827ce7dfc"
          },
          {
            "name": "X icone",
            "expression": [
              "",
              "VAR _current_mth=CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"X\")",
              "VAR _pm_mth=CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"X\")",
              "VAR _mom=DIVIDE(_current_mth,_pm_mth)*100",
              "VAR _icone_rep=IF(_mom>100, 10,ROUND(_mom/10,0))",
              "VAR _final= REPT([Filled Dot icone],_icone_rep)& REPT([Dot icone],10-_icone_rep)",
              "Return",
              "_final"
            ],
            "lineageTag": "31cf4f86-9d08-44cb-bd6b-c9babfa999ec"
          },
          {
            "name": "Baby Boomers",
            "expression": [
              "",
              "VAR _current_mth=CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\")",
              "VAR _pm_mth=CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\")",
              "VAR _mom=DIVIDE(_current_mth,_pm_mth)*100",
              "VAR _icone_rep=IF(_mom>100, 10,ROUND(_mom/10,0))",
              "VAR _final= REPT([Filled Dot icone],_icone_rep)& REPT([Dot icone],10-_icone_rep)",
              "Return",
              "_final"
            ],
            "lineageTag": "3031ec19-8753-427e-beda-237943866f46"
          },
          {
            "name": "Z (iGen)",
            "expression": [
              "",
              "VAR _current_mth=CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\")",
              "VAR _pm_mth=CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\")",
              "VAR _mom=DIVIDE(_current_mth,_pm_mth)*100",
              "VAR _icone_rep=IF(_mom>100, 10,ROUND(_mom/10,0))",
              "VAR _final= REPT([Filled Dot icone],_icone_rep)& REPT([Dot icone],10-_icone_rep)",
              "Return",
              "_final"
            ],
            "lineageTag": "6c0535e6-a3ad-4b98-b8fa-edf4fff82edf"
          },
          {
            "name": "Y label",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\"),  \"#,##0,.0\")",
              "VAR _tab= \"  \"",
              "VAR _gen=\"Y\"",
              "VAR _tabnr=13-len(_gen)",
              "VAR _final= _gen & REPT(_tab,_tabnr) & _current_mth & \" / \" & _pm_mth",
              "Return",
              "_final"
            ],
            "lineageTag": "0b942a90-3906-4c51-8553-94bb3d1c5773"
          },
          {
            "name": "U+200F",
            "expression": "\"U+200F\"",
            "lineageTag": "bc429f87-aff4-46cf-af33-132542d5fb22"
          },
          {
            "name": "U+200E",
            "expression": "\"U+200E\"",
            "lineageTag": "ee09f06b-fe91-46bd-977f-54e80f2cb849"
          },
          {
            "name": "X label",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"X\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"X\"),  \"#,##0,.0\")",
              "VAR _tab= \"  \"",
              "VAR _gen=\"X\"",
              "VAR _tabnr=13-len(_gen)",
              "VAR _final= _gen & REPT(_tab,_tabnr) & _current_mth & \" / \" & _pm_mth",
              "Return",
              "_final"
            ],
            "lineageTag": "b42be765-e15b-4a90-985e-d12fb9011f05"
          },
          {
            "name": "Baby Boomers label",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\"),  \"#,##0,.0\")",
              "VAR _tab= \"  \"",
              "VAR _gen=\"Baby Boomers\"",
              "VAR _tabnr=13-len(_gen)",
              "VAR _final= _gen & REPT(_tab,_tabnr) & _current_mth & \" / \" & _pm_mth",
              "Return",
              "_final"
            ],
            "lineageTag": "6439038f-9b68-4823-9837-9961dfba9ab1"
          },
          {
            "name": "Z label",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\"),  \"#,##0,.0\")",
              "VAR _tab= \"  \"",
              "VAR _gen=\"Z (iGen)\"",
              "VAR _tabnr=13-len(_gen)",
              "VAR _final= _gen & REPT(_tab,_tabnr) & _current_mth & \" / \" & _pm_mth",
              "Return",
              "_final"
            ],
            "lineageTag": "c43b0ffa-ebfd-4340-817b-bf08b9bf6c9f"
          },
          {
            "name": "Y value %",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Y (Millennials)\"),  \"#,##0,.0\")",
              "",
              "VAR _final=  divide(_current_mth,_pm_mth)",
              "Return",
              "_final"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "775ec770-a033-4753-9bb7-34ae277e2b58"
          },
          {
            "name": "X value %",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"X\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"X\"),  \"#,##0,.0\")",
              "VAR _final= Divide( _current_mth, _pm_mth)",
              "Return",
              "_final"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e71566a4-e6a4-45d0-8b4b-9090ff1dac3e"
          },
          {
            "name": "Baby Boomers value %",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Baby Boomers\"),  \"#,##0,.0\")",
              "VAR _final= Divide(_current_mth, _pm_mth)",
              "Return",
              "_final"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b5935cac-5c63-4c45-b37b-7a4c060b0c3e"
          },
          {
            "name": "Z value %",
            "expression": [
              "",
              "VAR _current_mth=FORMAT(CALCULATE([Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\"), \"#,##0,.0\")",
              "VAR _pm_mth=FORMAT(CALCULATE([PM_Mth2Date], 'Sales Raw Data'[Generation]=\"Z (iGen)\"),  \"#,##0,.0\")",
              "VAR _final= Divide(_current_mth, _pm_mth)",
              "Return",
              "_final"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "90142ee2-6e1f-4a46-a8ff-b74c431822f5"
          },
          {
            "name": "Label",
            "expression": "-1",
            "formatString": "0",
            "lineageTag": "651f22c5-255f-498a-89c7-4d904a5c4a1b"
          },
          {
            "name": "Label Sales by State",
            "expression": [
              "",
              "VAR _tab= \"  \"",
              "VAR _result= SELECTEDVALUE('Sales Raw Data'[State]) & REPT(_tab,4) & FORMAT(DIVIDE([Total Sales],[Total Sales (PM)])-1, \"+0.0%;-0.0%\")",
              "Return",
              "_result"
            ],
            "lineageTag": "329e109f-bac5-42ff-9ec7-7460c5e3e0a3"
          },
          {
            "name": "Opaque Area Sparkline",
            "expression": [
              "",
              "// line and area colour - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>",
              "        <stop stop-color='navy' offset='0' />",
              "        <stop stop-color='transparent' offset='1' />",
              "    </linearGradient>",
              "</defs>\"",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Date'[Date])",
              "VAR XMaxDate = MAX('Date'[Date])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values('Date'[Date]),CALCULATE([Total Sales]))",
              "VAR YMaxValue = MAXX(Values('Date'[Date]),CALCULATE([Total Sales]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Date','Date'[Date]),",
              "        \"X\",INT(150 * DIVIDE('Date'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Total Sales] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", 'Date'[Date])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 0 150 50'>\" & Defs &",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='navy' ",
              "      stroke-width='3' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/></svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "2decb8ed-d173-4418-a854-bbac2d7122d1"
          },
          {
            "name": "TU_Opaque Area Sparkline",
            "expression": [
              "",
              "// line and area colour - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>",
              "        <stop stop-color='navy' offset='0' />",
              "        <stop stop-color='transparent' offset='1' />",
              "    </linearGradient>",
              "</defs>\"",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Date'[Date])",
              "VAR XMaxDate = MAX('Date'[Date])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values('Date'[Date]),CALCULATE([Total Units]))",
              "VAR YMaxValue = MAXX(Values('Date'[Date]),CALCULATE([Total Units]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Date','Date'[Date]),",
              "        \"X\",INT(150 * DIVIDE('Date'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Total Units] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", 'Date'[Date])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 0 150 50'>\" & Defs &",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='navy' ",
              "      stroke-width='3' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/></svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "e3ac9a57-4c9b-4542-9599-0417030b2863"
          },
          {
            "name": "TP_Opaque Area Sparkline",
            "expression": [
              "",
              "// line and area colour - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR Defs = \"<defs>",
              "    <linearGradient id='grad' x1='0' y1='25' x2='0' y2='50' gradientUnits='userSpaceOnUse'>",
              "        <stop stop-color='navy' offset='0' />",
              "        <stop stop-color='transparent' offset='1' />",
              "    </linearGradient>",
              "</defs>\"",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Date'[Date])",
              "VAR XMaxDate = MAX('Date'[Date])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values('Date'[Date]),CALCULATE([Total Profit]))",
              "VAR YMaxValue = MAXX(Values('Date'[Date]),CALCULATE([Total Profit]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Date','Date'[Date]),",
              "        \"X\",INT(150 * DIVIDE('Date'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Total Profit] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", 'Date'[Date])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='0 0 150 50'>\" & Defs &",
              "     \"<polyline fill='url(#grad)' fill-opacity='0.3' stroke='navy' ",
              "      stroke-width='3' points=' 0 50 \" & Lines & ",
              "      \" 150 150 Z '/></svg>\"",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "7cfe82ae-3321-4c7a-bac6-707df89a2c54"
          },
          {
            "name": "_PieChart",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "// Derived from Martens",
              "    // Values",
              "\tVAR Percentage =  [Total Margine] // value has to be >= 0 and <=1",
              "\tVAR Colour = \"navy\" ",
              "\tVAR CirclePercent = 180 - (IF(Percentage > .9999, .9999, Percentage) * 360)",
              "\tVAR ShortDistance = if(CirclePercent < 0, 1,0)",
              "\tVAR Radians = RADIANS(CirclePercent)",
              "\tVAR XArcEnd = sin(Radians)*.8",
              "\tVAR YArcEnd = cos(Radians)*.8",
              "    // svg string ",
              "\tVAR svgHeader = ",
              "    \"data:image/svg+xml;utf8,<svg width='30' height='30' xmlns:svg='http://www.w3.org/2000/svg' xmlns='http://www.w3.org/2000/svg' viewBox='-1 -1 2 2'>\" ",
              "\tVAR BackgroundArc =\"<path d='M 0 -.8 A 0.8 0.8 0 1 1 \"&sin(RADIANS(-179.99))*.8&\" \"& cos(RADIANS(-179.99))*.8&\"  L 0 0 z' fill='lightsteelblue'></path>\" ",
              "\tVAR Arc =\"<path d='M 0 -.8 A 0.8 0.8 0 \" & ShortDistance & \" 1 \" & XArcEnd & \" \" & YArcEnd & \"  L 0 0 z' fill='\" & Colour & \"'></path>\"",
              "\tVAR svgFooter = \"</svg>\"",
              "    return svgHeader & BackgroundArc & Arc & svgFooter"
            ],
            "lineageTag": "dda18245-f3e9-4632-830e-695b30448314"
          },
          {
            "name": "Icon Callout Progress",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "--- Field to sort the measures by in a table ---",
              "VAR SORT = [Total Margine]*100",
              "--- Progress Bar Info ---",
              "VAR PERCENTAGEFILL = [Total Margine]*100",
              "VAR BarColour = \"Navy\"",
              "--- svg symbol in its own coordinate system ---",
              "--- replace with your own svg but ensure to place id tag id='mySymbol'---",
              "VAR Symbol =   ",
              "  \"<symbol id='mySymbol' width='10' height='10' viewBox='0 0 2 2'>",
              "    <circle cx='1' cy='1' r='1' />",
              "  </symbol>\"",
              "VAR Symbol1 =   ",
              "  \"<symbol id='mySymbol' width='15' height='15' viewBox='-1 -1 2 2'>",
              "    <path fill='#F4BF3D' d='M0,.5L.6,.8L.5,.1L1,-.3L.3,-.4L0,-1L-.3,-.4L-1,-.3L-.5,.1L-.6,.8L0,.5Z'/>",
              "  </symbol>\"",
              "VAR Symbol2 =   ",
              "  \"<symbol id='mySymbol' width='15' height='15' viewBox='-1 -1 2 2'>",
              "    <path d='M.83.09,0,.91-.83.09a.59.59,0,0,1,0-.83A.59.59,0,0,1,0-.74a.59.59,0,0,1,.83,0A.59.59,0,0,1,.83.09Z'/>",
              "  </symbol>\"",
              "VAR Symbol3 =   ",
              "  \"<symbol id='mySymbol' width='15' height='15' viewBox='0 0 1220 1601'>",
              "    <g transform='translate(-1681 -906)'><path d='M2342 993.77C2342 962.969 2366.97 938 2397.77 938L2813.2 938C2844 938 2868.97 962.969 2868.97 993.77L2868.97 2419.23C2868.97 2450.03 2844 2475 2813.2 2475L2397.77 2475C2366.97 2475 2342 2450.03 2342 2419.23Z' stroke='#FFFFFF' stroke-width='64.1667' stroke-miterlimit='8' fill='#F4BF3D' fill-rule='evenodd'/><path d='M2032 1380.79C2032 1349.98 2056.98 1325 2087.8 1325L2503.48 1325C2534.3 1325 2559.28 1349.98 2559.28 1380.79 2559.85 1745.42 2560.43 2110.05 2561 2474.68 2532.64 2475.43 2534.3 2474.63 2503.48 2474.63L2087.8 2474.63C2056.98 2474.63 2032 2449.65 2032 2418.84L2032 1380.79Z' stroke='#FFFFFF' stroke-width='64.1667' stroke-miterlimit='8' fill='#F4BF3D' fill-rule='evenodd'/><path d='M1713 1769.35C1713 1732.15 1743.21 1702 1780.47 1702L2167.81 1702C2205.07 1702 2235.28 1732.15 2235.28 1769.35 2235.85 2003.9 2236.43 2238.45 2237 2473L2167.81 2472.79 1780.47 2472.79C1743.21 2472.79 1713 2442.63 1713 2405.43L1713 1769.35Z' stroke='#FFFFFF' stroke-width='64.1667' stroke-miterlimit='8' fill='#F4BF3D' fill-rule='evenodd'/></g>",
              "  </symbol>\"",
              "VAR symbol4 = \"<svg xmlns='http://www.w3.org/2000/svg' width='15' height='15' viewBox='0 0 100 100'>",
              "  <symbol id='bike' viewBox='0 0 100 100'>",
              "    <circle cx='30' cy='70' r='15' stroke='black' stroke-width='2' fill='none' />",
              "    <circle cx='70' cy='70' r='15' stroke='black' stroke-width='2' fill='none' />",
              "    <line x1='30' y1='70' x2='50' y2='50' stroke='black' stroke-width='2' />",
              "    <line x1='50' y1='50' x2='70' y2='70' stroke='black' stroke-width='2' />",
              "    <line x1='50' y1='50' x2='50' y2='30' stroke='black' stroke-width='2' />",
              "    <line x1='50' y1='30' x2='35' y2='45' stroke='black' stroke-width='2' />",
              "    <line x1='50' y1='30' x2='65' y2='45' stroke='black' stroke-width='2' />",
              "    <circle cx='50' cy='50' r='3' stroke='black' stroke-width='2' fill='black' />",
              "    <line x1='50' y1='50' x2='60' y2='60' stroke='black' stroke-width='2' />",
              "  </symbol>",
              "  <use href='#bike' x='0' y='0' width='100' height='100' />",
              "</svg>\"",
              "VAR symbol5 =  \"<svg xmlns='http://www.w3.org/2000/svg' width='15' height='15' viewBox='0 0 100 100'>",
              "  <symbol id='bikeWheel' viewBox='0 0 100 100'>",
              "    <!-- Zewntrzna opona -->",
              "    <circle cx='50' cy='50' r='45' stroke='black' stroke-width='5' fill='none' />",
              "    <!-- Piasta -->",
              "    <circle cx='50' cy='50' r='8' stroke='black' stroke-width='2' fill='black' />",
              "    <!-- Szprychy -->",
              "    <line x1='50' y1='5' x2='50' y2='95' stroke='black' stroke-width='2' />",
              "    <line x1='5' y1='50' x2='95' y2='50' stroke='black' stroke-width='2' />",
              "    <line x1='15' y1='15' x2='85' y2='85' stroke='black' stroke-width='2' />",
              "    <line x1='85' y1='15' x2='15' y2='85' stroke='black' stroke-width='2' />",
              "  </symbol>",
              "",
              "  <!-- Uycie symbolu koa rowerowego -->",
              "  <use href='#bikeWheel' x='0' y='0' width='100' height='100' />",
              "</svg>\"",
              "",
              "",
              "RETURN",
              "",
              "\"data:image/svg+xml;utf8,\" & ",
              "\"<svg desc = '\" & SORT & \"' width='100' height='25' viewBox='-2 -2 105 20' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' display= 'block'  overflow='visible'>",
              "<rect id='track' x='0' y='15' rx='0' ry='0' width='100' height='25' fill='#D0D0D0' />",
              "\" & symbol5  & \"",
              "<rect id='fill' x='0' y='15' rx='0' ry='0' width=\"& \"'\"& PERCENTAGEFILL &\"'\"&\" height='10' fill='\"&BarColour&\"'></rect>",
              "<use href='#mySymbol' x='0' y='-2' style='opacity:1.0' />",
              "<text x='17' y='8' font-weight='bold' font-family='Segoe UI, sans-serif' >\"&FORMAT(PERCENTAGEFILL/100, \"0%\")&\"</text>",
              "</svg>\"",
              ""
            ],
            "lineageTag": "475549b3-289c-4e14-91d0-a5647054c8e7"
          },
          {
            "name": "Dummy",
            "expression": "\"BW\"",
            "lineageTag": "f3ccbaf2-3ea7-43f9-bf82-5190b45742f9"
          },
          {
            "name": "Label2",
            "expression": "If([Total Sales]>[Total Sales (PM)],[Total Sales],[Total Sales (PM)])",
            "formatString": "0",
            "lineageTag": "fecaf55f-6d70-4f18-9f52-f0b887d28b39"
          },
          {
            "name": "Label Comparison",
            "expression": [
              "",
              "VAR _current_value=[Total Sales]",
              "VAR _variance_vs_pm=[Total Sales]-[Total Sales (PM)]",
              "VAR _result= Format(_current_value,\"#,##0,\") & \"k|\" & Format(_variance_vs_pm,\"#,##0,\") & \"k\"",
              "Return",
              "_result"
            ],
            "lineageTag": "2ce453f3-7ad3-42e1-a5b6-e30e7aa31c36"
          },
          {
            "name": "Color Label",
            "expression": "If ( [Total Sales]>[Total Sales (PM)], \"Green\", \"Red\")",
            "lineageTag": "95e95e7d-703e-45a3-9fd0-6a7beb5d542b"
          },
          {
            "name": "Sparkline Points",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)",
              "VAR LineColour = \"%237469c8\"",
              "VAR PointColour = \"white\"",
              "",
              "// \"Date\" field used in this example along the X axis",
              "VAR XMinDate = MIN('Date'[Date])",
              "VAR XMaxDate = MAX('Date'[Date])",
              "",
              "// Obtain overall min and overall max measure values when evaluated for each date",
              "VAR YMinValue = MINX(Values('Date'[Date]),CALCULATE([Total Sales]))",
              "VAR YMaxValue = MAXX(Values('Date'[Date]),CALCULATE([Total Sales]))",
              "",
              "// Build table of X & Y coordinates and fit to 50 x 150 viewbox",
              "VAR SparklineTable = ADDCOLUMNS(",
              "    SUMMARIZE('Date','Date'[Date]),",
              "        \"X\",INT(150 * DIVIDE('Date'[Date] - XMinDate, XMaxDate - XMinDate)),",
              "        \"Y\",INT(50 * DIVIDE([Total Sales] - YMinValue,YMaxValue - YMinValue)))",
              "",
              "// Concatenate X & Y coordinates to build the sparkline",
              "VAR Lines = CONCATENATEX(SparklineTable,[X] & \",\" & 50-[Y],\" \", 'Date'[Date])",
              "VAR PointTable=",
              "    ADDCOLUMNS(",
              "        SUMMARIZE('Date','Date'[Date]),",
              "            \"@Colour\",IF([Total Sales]=YMaxValue,\"Green\",IF([Total Sales]=YMinValue,\"Red\",LineColour)),",
              "        \"@Points\", \"<circle cx='\"&INT(150 * DIVIDE('Date'[Date] - XMinDate, XMaxDate - XMinDate))&\"' cy='\" & 50 -  INT(50 * DIVIDE([Total Sales] - YMinValue,YMaxValue - YMinValue)) & \"' r='3' stroke='\"&LineColour&\"' stroke-width='1'  fill='\"&LineColour&\"'/>\")",
              "",
              "// Last data points on the line",
              "VAR LastSparkYValue = MAXX( FILTER(SparklineTable, 'Date'[Date] = XMaxDate), [Y])",
              "VAR LastSparkXValue = MAXX( FILTER(SparklineTable, 'Date'[Date] = XMaxDate), [X])",
              "",
              "// Add to SVG, and verify Data Category is set to Image URL for this measure",
              "VAR SVGImageURL = ",
              "    \"data:image/svg+xml;utf8,\" & ",
              "    --- gradient---",
              "    \"<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>\" &",
              "    --- Lines---",
              "    \"<polyline ",
              "        fill='transparent' stroke='\" & LineColour & \"' ",
              "        stroke-linecap='round' stroke-linejoin='round' ",
              "        stroke-width='2' points=' \" & Lines & ",
              "      \" '/>\" &",
              "    --- Last Point---",
              "        CONCATENATEX(PointTable,[@Points]) &",
              "        \"<circle cx='\"& LastSparkXValue & \"' cy='\" & 50 - LastSparkYValue & \"' r='4' stroke='\" & LineColour & \"' stroke-width='3' fill='\" & PointColour & \"' />\" &",
              "        \"</svg>\"",
              "        ",
              "RETURN SVGImageURL"
            ],
            "lineageTag": "2836bba3-8b40-4ab3-a66e-04f2e3ed4f9d"
          }
        ],
        "partitions": [
          {
            "name": "Calculations",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Disconnected Date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b0c646fe4d764fc4b06c4d6a73ed1cbc"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "634bb0fd-8fe6-4f8c-b02b-fcf9c0ffb919",
            "sourceColumn": "Date[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd"
                },
                "isDefault": true,
                "relationship": "f50c9399-05f6-4d14-aab5-9b6e4e986739"
              }
            ]
          },
          {
            "name": "Date Integer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "969c34b7-b57d-4a0f-a0b2-44b8e4a47807",
            "sourceColumn": "Date[Date Integer]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fa4117bc-ecfc-4fba-9fc6-9d41d0d7928c",
            "sourceColumn": "Date[Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "83ab0332-f1a7-44c5-8512-7cbb853ab55f",
            "sourceColumn": "Date[Year Default]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YYYY-MM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c9e09c3f-ff78-4ea0-bf8e-59f9face3f8a",
            "sourceColumn": "Date[YYYY-MM]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month-Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f336ee54-0331-49f9-aca1-73ca62173a51",
            "sourceColumn": "Date[Month-Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "901c6933-e70f-4d6c-9c71-c2bf48dfdb93",
            "sourceColumn": "Date[Month Of Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "cc93ae4f-4370-4174-9a91-3999a204c0fb",
            "sourceColumn": "Date[Month Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7cc4699a-13c7-4a80-92f0-9cc31c317361",
            "sourceColumn": "Date[Month Name Short]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Name Default",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8077aab4-d082-43cd-baab-5a3e4c04ba83",
            "sourceColumn": "Date[Month Name Default]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f0f7b391-a37f-4c60-9666-95e4f3f693a8",
            "sourceColumn": "Date[Start of Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35"
                },
                "isDefault": true,
                "relationship": "3b237f3a-c3bf-440d-ad21-cff64c3362aa"
              }
            ]
          },
          {
            "name": "End of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ec3be6f7-fc3e-4484-8221-2e41d8080a15",
            "sourceColumn": "Date[End of Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf"
                },
                "isDefault": true,
                "relationship": "8e958b82-1e0f-415f-9393-5cf90c51023e"
              }
            ]
          },
          {
            "name": "Days in Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e51bc00d-b94e-4927-ae4b-2a0bcc1ef0ad",
            "sourceColumn": "Date[Days in Month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ISO Weeknumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ebdc011b-2d17-4241-a07b-b94533acbaee",
            "sourceColumn": "Date[ISO Weeknumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ISO Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "3318e05e-eedc-48b5-bc2f-a34a0e82b7b2",
            "sourceColumn": "Date[ISO Year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c4b6663d-5a10-4b65-bffc-c87a1253d089",
            "sourceColumn": "Date[Start of Week]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7"
                },
                "isDefault": true,
                "relationship": "bacc3aeb-854a-4ed8-8b4b-0742ab4924a7"
              }
            ]
          },
          {
            "name": "Quarter Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "04cccd17-bd59-4836-b235-6dcfd0a0dddd",
            "sourceColumn": "Date[Quarter Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2532a22a-781f-40da-99d7-422f848aabce",
            "sourceColumn": "Date[Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year-Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "624a85ea-eec4-4317-a31d-75e5e2b2b8d0",
            "sourceColumn": "Date[Year-Quarter]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1145a024-319f-4503-bf74-5d3fb0a53a52",
            "sourceColumn": "Date[Day Name]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Name Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d41da494-c227-4441-912e-79af97e11c3c",
            "sourceColumn": "Date[Day Name Short]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "fe0326b6-ed40-4c7f-a52e-630d3f6d21c0",
            "sourceColumn": "Date[Day of Month Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Week Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b7199fa8-1420-4e83-a721-aa6014fa3483",
            "sourceColumn": "Date[Day of Week Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day of Year Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ceedaab7-ddad-46c5-a6cd-c65280ec4511",
            "sourceColumn": "Date[Day of Year Number]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6d44658c-9341-475d-b322-893d13c04dc6",
            "sourceColumn": "Date[Day Offset]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Week Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6107ed43-c79e-4af1-800a-aeff643fc434",
            "sourceColumn": "Date[Week Offset]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Month Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "93a8cf6c-4a39-45dd-acef-dd7772a03985",
            "sourceColumn": "Date[Month Offset]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Quarter Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "615a8400-f5b8-4130-9b30-808ff0d55096",
            "sourceColumn": "Date[Quarter Offset]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Offset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b5499747-717e-4919-ac73-ab03d7186eeb",
            "sourceColumn": "Date[Year Offset]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Weekend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "67135475-2385-4ffb-9a71-a9b2c103ba26",
            "sourceColumn": "Date[Is Weekend]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Is Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "69d6e734-cb40-496c-8bde-c030b7644a10",
            "sourceColumn": "Date[Is Weekday]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "53ed0e4e-e7de-4a8c-a970-78ba55dd46a2",
        "partitions": [
          {
            "name": "Disconnected Date",
            "mode": "import",
            "source": {
              "expression": "'Date'",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "acbce88e-ab16-4027-8de1-606ba259da2a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0d8dc898-1718-4755-b810-91c6097e8417",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5222a017-4bf9-4d78-8efc-4b5860d7272f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0c2b536f-178c-4d87-8aae-54408582cc0a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47b16030-d619-4e6e-9ce9-da93974cc283",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "36475b8f-3c07-4946-8b0a-702a0364c7f2",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "91fead7c-b1e7-4557-a179-ac3093f06b3f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a2bb2a96-4251-4588-838d-7e570474b5a0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "11c98b72-68c6-4189-a302-e07144f358bc",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c729a64e-c56f-467f-9fcd-2775ccdd3fa2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "262fccb9-235b-41da-98ba-6bd61569f367",
                "ordinal": 3
              }
            ],
            "lineageTag": "4b229675-1915-4509-8ef8-c7616bb5a278"
          }
        ],
        "isHidden": true,
        "lineageTag": "5a796fef-3489-4cf8-84ba-492f38bd41a5",
        "partitions": [
          {
            "name": "LocalDateTable_f56e1c5a-0933-4d4e-ab23-8cf13d6b5efd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Disconnected Date'[Date])), 1, 1), Date(Year(MAX('Disconnected Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8110cba1-262d-4292-9212-a36653dbd972",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5ee3ea48-dcca-4fbf-b5ab-b544f9eac1a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3804b19b-b141-4ae0-963e-39c12a94ea0b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "04648704-0c2a-4633-b903-f646dfe9f6a2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c566bb65-4aa1-4050-8d48-2ff80f04d933",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2148c683-3334-4012-8ad8-7d1c8066ca93",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f10d0deb-2c5a-4c1d-9a20-9d594ff51a48",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "52c8112f-948e-483a-b409-640f135d0e6b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cb755353-7278-458c-84a8-ca1960b7fb0e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "61bd5205-ee23-4764-b251-2d85eb0128b7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0c844614-9e16-484b-8db2-b84f2154cc0c",
                "ordinal": 3
              }
            ],
            "lineageTag": "99b5395f-4217-4d65-a312-bd002d575628"
          }
        ],
        "isHidden": true,
        "lineageTag": "2c296d5c-70ae-4c83-9681-2b7efcb1b25c",
        "partitions": [
          {
            "name": "LocalDateTable_aceb5a80-0479-4ec2-a8ec-7441b8cdcf35",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Disconnected Date'[Start of Month])), 1, 1), Date(Year(MAX('Disconnected Date'[Start of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "aeba0bd8-71ea-464a-b4e3-70010028edf5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "88b5c5c3-dbea-4dfc-9164-9147f56d6cc6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0f4681b7-e21f-4e72-abf9-a400ba89a515",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1fdcb0e7-e70d-4ddf-b076-3983c64ae2d7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b5e2b62b-39a2-4a91-a4ef-b8651d47b478",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f8bc62eb-1d59-483b-9b86-7d845d1c4dad",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "61372507-27b9-4678-989a-fe22f622ec0f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9c2f1883-aa98-422d-ab00-a63e799c3571",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "12bad96d-fee2-4b61-9390-b8db7c3be6ed",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "91c8f5e7-91aa-45af-949e-367e8aad890b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e42c8a97-fe99-43a5-9516-9c1a4937d61f",
                "ordinal": 3
              }
            ],
            "lineageTag": "2c225f78-b3b5-4888-a440-7ce5783a1039"
          }
        ],
        "isHidden": true,
        "lineageTag": "f10263d1-6194-4f8d-b9af-48b763bce7b3",
        "partitions": [
          {
            "name": "LocalDateTable_2567927f-5e0c-41e6-8b02-40e13e9202cf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Disconnected Date'[End of Month])), 1, 1), Date(Year(MAX('Disconnected Date'[End of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eaefe38b-c071-4f99-9655-c2e6d22ade81",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ca8c7ac7-d189-4220-a03a-9b752712e547",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7bbea8be-2602-4c21-b25a-1548972b3667",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7cc0f4d2-715f-48cd-b7d6-3fc867695599",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3e28b42f-cab4-422b-8f15-c904e45285c1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "40102d87-d075-40e2-b11c-c9e55c8921fd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ad0bdc42-947a-48f3-a9a0-5723a10aa394",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "70e176e1-6def-4ee6-8b8c-880eefa246ec",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cdfefa02-9cc7-442a-b576-3a98f66592e6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f4e61306-8534-47bf-be9b-57b8a0f1fb64",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "319d73ea-794f-4f0c-bb8c-92566ec59677",
                "ordinal": 3
              }
            ],
            "lineageTag": "bdb26c7d-5e54-4dcc-bb36-05ec27b84a92"
          }
        ],
        "isHidden": true,
        "lineageTag": "d17205f2-99c1-4e28-95f0-4a7733f4bad8",
        "partitions": [
          {
            "name": "LocalDateTable_91065902-6b20-4cca-9930-0b40db90afd7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Disconnected Date'[Start of Week])), 1, 1), Date(Year(MAX('Disconnected Date'[Start of Week])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ccb78f1409584d8d9ca38fc430af2ad0"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "2b361afd-ac9e-47e7-bb9d-35fa7b4ab2f2",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f89efc2d-026f-4ba9-805e-aa933578aec3",
        "measures": [
          {
            "name": "Parameter Value",
            "expression": "SELECTEDVALUE('Parameter'[Parameter])",
            "formatString": "0",
            "lineageTag": "f6d699e7-2936-4ca3-ac7e-343e047750f2"
          }
        ],
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 3, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Customer",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b02fba370a0847209c4ffa2a94725245"
          }
        ],
        "columns": [
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "dff95945-1ea0-4eba-9036-ce6bc273a37c",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Customer Fields"
                }
              ]
            },
            "sortByColumn": "Customer Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "4828af46-7ef0-4df1-b640-9a5f5d7aa73b",
            "sortByColumn": "Customer Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Customer Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "922de667-2f82-413f-a290-e90c3d98028a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9efe5c13-19f9-45c0-b3a9-b7501338ed35",
        "partitions": [
          {
            "name": "Customer",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Customer Age\", NAMEOF('Sales Raw Data'[Customer Age]), 0),",
                "    (\"Generation\", NAMEOF('Sales Raw Data'[Generation]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ParamRows",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0634178ea6ac475da952d32e9a70df5d"
          }
        ],
        "columns": [
          {
            "name": "ParamRows",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f3869f2f-d60a-4c26-ae91-0ae5ce632393",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "ParamRows Fields"
                }
              ]
            },
            "sortByColumn": "ParamRows Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamRows Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "62d1c40f-bfb0-46b5-8b6e-0ed6de50dc6a",
            "sortByColumn": "ParamRows Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamRows Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "8ebf6ac4-3ed4-4b4d-8ec4-650427efc844",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5d46fe89-e0cd-4a66-85e5-ad797e382bf7",
        "partitions": [
          {
            "name": "ParamRows",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Generation\", NAMEOF('Sales Raw Data'[Generation]), 0),",
                "    (\"Product Category\", NAMEOF('Sales Raw Data'[Product Category]), 1),",
                "    (\"Sub Category\", NAMEOF('Sales Raw Data'[Sub Category]), 2),",
                "    (\"Customer Gender\", NAMEOF('Sales Raw Data'[Customer Gender]), 3),",
                "    (\"State\", NAMEOF('Sales Raw Data'[State]), 4),",
                "    (\"Country\", NAMEOF('Sales Raw Data'[Country]), 5),",
                "    (\"Year\", NAMEOF('Date'[Year]), 6),",
                "    (\"Month Name Short\", NAMEOF('Date'[Month Name Short]), 7)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ParamCol",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "4e768fd819b247868f4b0a2a8264d057"
          }
        ],
        "columns": [
          {
            "name": "ParamCol",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "4b4506de-128a-41e3-b703-e85f91308fb0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "ParamCol Fields"
                }
              ]
            },
            "sortByColumn": "ParamCol Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamCol Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dd6a25b2-99b7-4652-bc32-11257e23bfb8",
            "sortByColumn": "ParamCol Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamCol Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "153f33b3-7fb1-430c-afa9-ba5606bde066",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "16d2987c-e8c5-440f-a45e-c3ffc060f9a6",
        "partitions": [
          {
            "name": "ParamCol",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Generation\", NAMEOF('Sales Raw Data'[Generation]), 0),",
                "    (\"Product Category\", NAMEOF('Sales Raw Data'[Product Category]), 1),",
                "    (\"Sub Category\", NAMEOF('Sales Raw Data'[Sub Category]), 2),",
                "    (\"Customer Gender\", NAMEOF('Sales Raw Data'[Customer Gender]), 3),",
                "    (\"State\", NAMEOF('Sales Raw Data'[State]), 4),",
                "    (\"Country\", NAMEOF('Sales Raw Data'[Country]), 5),",
                "    (\"Year\", NAMEOF('Date'[Year]), 6),",
                "    (\"Month Name Short\", NAMEOF('Date'[Month Name Short]), 7)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ParamValue",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "14d4378a9f294afea659ba1d50c8e014"
          }
        ],
        "columns": [
          {
            "name": "ParamValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5e1c8035-5dd1-4307-8a5d-9cce09de8bd5",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "ParamValue Fields"
                }
              ]
            },
            "sortByColumn": "ParamValue Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamValue Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "14c03ca8-7390-4340-ac6c-855b926aaf6d",
            "sortByColumn": "ParamValue Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamValue Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7f533d36-2f4f-4535-b8d8-a50ab3cce6d8",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "db78c931-1c14-4a6f-9418-c51cc2cb4a22",
        "partitions": [
          {
            "name": "ParamValue",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Sales\", NAMEOF('Sales Raw Data'[Sales]), 0),",
                "    (\"Revenue\", NAMEOF('Sales Raw Data'[Revenue]), 1),",
                "    (\"Quantity\", NAMEOF('Sales Raw Data'[Quantity]), 2),",
                "    (\"Profit\", NAMEOF('Sales Raw Data'[Profit]), 3),",
                "    (\"Cost\", NAMEOF('Sales Raw Data'[Cost]), 4),",
                "    (\"Unit Price\", NAMEOF('Sales Raw Data'[Unit Price]), 5),",
                "    (\"Unit Cost\", NAMEOF('Sales Raw Data'[Unit Cost]), 6),",
                "    (\"YTD Sales\", NAMEOF('Sales Raw Data'[YTD Sales]), 7)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "ParamValues",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "f1edf64596c9407c8594fe50e153a87f"
          }
        ],
        "columns": [
          {
            "name": "ParamValues",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "66636cd9-fb3d-42d7-b935-8af29bdd8e62",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "ParamValues Fields"
                }
              ]
            },
            "sortByColumn": "ParamValues Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamValues Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "09bcfe9a-5659-4bf2-b365-22067e28db0d",
            "sortByColumn": "ParamValues Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "ParamValues Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "caa6b3fb-e6f6-487d-b78a-c1e368c8924a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "7c604234-2960-4e72-9d2f-d0e6e478ad8b",
        "partitions": [
          {
            "name": "ParamValues",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Profit\", NAMEOF('Calculations'[Total Profit]), 0),",
                "    (\"Total Margine\", NAMEOF('Calculations'[Total Margine]), 1),",
                "    (\"Total Sales\", NAMEOF('Calculations'[Total Sales]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter 2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a14990bb9c5d4d04ac97e5212d920726"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "cbf7f48e-b1b6-41a7-8541-5162e2a2553f",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "dc888cac-3601-49d9-a283-8f6da3bbf94e",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7300a362-7b07-4bce-b44c-9afcc84014a9",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "8e297108-db7f-46e9-ab0f-7fa4383f6ff7",
        "partitions": [
          {
            "name": "Parameter 2",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"State\", NAMEOF('Sales Raw Data'[State]), 0),",
                "    (\"Generation\", NAMEOF('Sales Raw Data'[Generation]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter 3",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "07639f4f67964ebeb333c3282780bd03"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "8d5f3bb8-6752-4adc-b1c4-dc42650640a0",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "9b529312-7b54-4bbe-b198-24353d654d72",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7062ae43-26df-4fc9-bd24-35697e0eca04",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "fff9f87a-6bb6-4812-8f47-182aaabd8d6b",
        "partitions": [
          {
            "name": "Parameter 3",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Gender\", NAMEOF('Sales Raw Data'[Customer Gender]), 0),",
                "    (\"Generation\", NAMEOF('Sales Raw Data'[Generation]), 1),",
                "    (\"State\", NAMEOF('Sales Raw Data'[State]), 2)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Product Type Order",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8c81165369c24e0ab9f52406f879a673"
          }
        ],
        "columns": [
          {
            "name": "Product Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "001898da-9daf-46ed-9145-1e7a1038e90a",
            "sortByColumn": "Sales by Product",
            "sourceColumn": "Sales Raw Data[Product Category]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Sales by Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6001f2ca-dcda-4465-9e31-67ad48fa1e6f",
            "sourceColumn": "[Sales by Product]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e07309b1-399c-420f-ae4e-90f0f9f021ec",
        "partitions": [
          {
            "name": "Product Type Order",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "\tSUMMARIZE(",
                "\t\t'Sales Raw Data',",
                "\t\t'Sales Raw Data'[Product Category],",
                "\t\t\"Sales by Product\", [SalesPerPoduct]",
                "\t)"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}